[package]
name = "t-browser"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
